### ISSUE TITLE
PartialOrderingMixin lacks a __slots__, which makes intrangeset have a __dict__

### ISSUE THREAD

**Issue by dcolascione** [runfalk/spans#10]
In [1]: import spans

In [2]: for cls in spans.intrangeset.mro():
   ...:     if cls.__module__.startswith("spans."):
   ...:         if not hasattr(cls, "__slots__"):
   ...:             print(cls)
   ...:             
<class 'spans._utils.PartialOrderingMixin'>

**Comment by runfalk** [comment]
Thank you for reporting this. I'll include it in a bugfix release shortly.
