### ISSUE TITLE
Union of ranges seems to be broken if upper_inc=True is set for the lower range

### ISSUE THREAD

**Issue by der-michik** [runfalk/spans#11]
I just noticed a strange bug in the behaviour of datetimeranges. Suppose I have two ranges a and b where `a.upper == b.lower`, e.g.:
```
>>> from datetime import datetime
>>> from spans import datetimerange
>>> dt1 = datetime(2018, 7, 20, 0, 0)
>>> dt2 = datetime(2018, 7, 20, 1, 0)
>>> dt3 = datetime(2018, 7, 20, 2, 0)
>>> a, b = datetimerange(dt1, dt2), datetimerange(dt2, dt3)
>>> a.upper == b.lower
True
```
I now want to calculate the union of these two ranges. According to the documentation, this is possible if the ranges do either overlap (i.e. `a.upper > b.lower`) or are adjacent to each other, (i.e. `a.upper == b.lower`). Let's try:
```
>>> a.union(b)
datetimerange([datetime.datetime(2018, 7, 20, 0, 0),datetime.datetime(2018, 7, 20, 2, 0)))
```
However, if the `upper_inc=True` argument is given for a, this fails:
```
>>> a = datetimerange(dt1, dt2, upper_inc=True)
>>> a.union(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/m/Pycharm/hmi/venv/lib/python3.5/site-packages/spans/types.py", line 488, in union
    raise ValueError("Ranges must be either adjacent or overlapping")
ValueError: Ranges must be either adjacent or overlapping
```
If we move `a.upper` only slightly, this works again as it should:
```
>>> from datetime import timedelta
>>> a = datetimerange(dt1, dt2+timedelta(milliseconds=1))
>>> a.union(b)
datetimerange([datetime.datetime(2018, 7, 20, 0, 0),datetime.datetime(2018, 7, 20, 2, 0)))
```
Line 487 of `types.py` is:
```
if a.upper <= b.lower and not a.adjacent(b):
```
The definition of `.adjacent()` starting in line 414 suggests, that two ranges are adjacent if, and only if `a.upper == b.lower and a.upper_inc != b.lower_inc`. As `a.upper_inc` is `True`, this is of course `False` and consequently, the exception is raised in line 488. In our case, `a` and `b` are overlapping since `a.upper` is in `a` and in `b` (where it is `b.lower`), so I think, the result of `.adjacent()` is correct here.

In order to get this right, `.union()` probably needs to look for `upper_inc` and `lower_inc` and must handle these cases differently. I will see if I can prepare a patch for this.

**Comment by runfalk** [comment]
Thank you for reporting this. Upper inclusivity is something I rarely use myself, which might by why this haven't surfaced earlier.

I'll await you patch. Otherwise please let me know if I should start working on it :)

I made a test case for it you can use. Please put it in `test_range.py`.

```python
def test_bug11_valid_union_call_detected_as_invalid():
    """
    `Bug #11 <https://github.com/runfalk/spans/issues/11>`_
    """
    start, middle, end = 0.0, 1.0, 2.0
    a = floatrange(start, middle, upper_inc=True)
    b = floatrange(middle, end)

    assert a.union(b) == floatrange(start, end)
```
