### ISSUE TITLE
floatrangeset union behavior when lower and upper limit are  same 

### ISSUE THREAD

**Issue by Myrtillus** [runfalk/spans#13]
Hi! 
Thank you for this awesome library! I don't know if the below is planned behaviour or error, see the examples:

Setting the lower and upper limit same

        a1 = spans.floatrangeset([])
        a1.add(spans.floatrange(10.,10.,upper_inc = True))

        a2 = spans.floatrangeset([])
        a2.add(spans.floatrange(10.,10.,upper_inc = True))

Trying to take the union causes an error

        a1.union(a2)

ValueError: Ranges must be either adjacent or overlapping

Increasing the length of the range and no error is raised.

        a1 = spans.floatrangeset([])
        a1.add(spans.floatrange(10.,11.,upper_inc = True))

        a2 = spans.floatrangeset([])
        a2.add(spans.floatrange(10.,11.,upper_inc = True))

        a1.union(a2)

**Comment by runfalk** [comment]
Glad you like it!

This certainly looks like a bug. I assume this affects all non-discrete range set types. The entire purpose of the range set types is to allow unions of non-adjacent/overlapping ranges.

If you want to give it a go PRs are always appreciated. Otherwise I'll look into it, but I can give no guarantees when that will be.

**Comment by der-michik** [comment]
Looks like this is the same bug as in #11. In the version I use with my patch from #12, it works as intended:

```
>>> import spans 
>>> a1 = spans.floatrangeset([]) 
>>> a1.add(spans.floatrange(10.,10.,upper_inc = True)) 
>>> a2 = spans.floatrangeset([]) 
>>> a2.add(spans.floatrange(10.,10.,upper_inc = True)) 
>>> a1.union(a2)
floatrangeset([floatrange([10.0,10.0])])
```

**Comment by runfalk** [comment]
Maybe I should get off my ass and make a new release then.

**Comment by Myrtillus** [comment]
I probably don't understand something in the usage of the rangesets. The following union operation also fails even if the zero length spans have been extended slightly.

error case example:

(Pdb) shutdown_rangeset
floatrangeset([floatrange([1515737730.0,1515737730.1]), floatrange([1515738120.0,1515738120.1])])

having tmp_span that should be unioned with the previous one.

(Pdb) tmpspan
floatrange([1515737550.0,1515738120.0])

Combining the tmpspan to shutdown rangeset with union leads to error: 

(Pdb) shutdown_rangeset.union(spans.floatrangeset([tmpspan]))
*** ValueError: Ranges must be either adjacent or overlapping

How should I overcome this issue?

**Comment by Myrtillus** [comment]
`#!/usr/bin/env python
# -*- coding: latin 1 -*-

import spans
import pdb

try:
    a1 = spans.floatrange(10.,11.,upper_inc =True)
    a2 = spans.floatrange(20.,21.,upper_inc =True)
    a3 = spans.floatrange(15.,21.,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)
    print "Works"
except:
    print "Fails"



try:
    a1 = spans.floatrange(10.,10.1,upper_inc =True)
    a2 = spans.floatrange(20.,20.1,upper_inc =True)
    a3 = spans.floatrange(15.,20.1,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)
    print "Works"
except:
    print "Fails"



try:
    # below works when the span size is 1.1

    a1 = spans.floatrange(1515737730.0 , 1515737731.1 , upper_inc =True)
    a2 = spans.floatrange(1515738120.0 , 1515738121.1 , upper_inc =True)
    a3 = spans.floatrange(1515737550.0 , 1515738121.0,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)

    print "Works"

except:
    print "Fails"



# below works when the span size is 0.1
try:
    a1 = spans.floatrange(7730.0 , 7730.1 , upper_inc =True)
    a2 = spans.floatrange(8120.0 , 8120.1 , upper_inc =True)
    a3 = spans.floatrange(7550.0 , 8120.0,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)

    print "Works"
except:
    print "Fails"



# below FAILS when the span size is 0.1

try:
    a1 = spans.floatrange(5737730.0 , 5737730.1 , upper_inc =True)
    a2 = spans.floatrange(5738120.0 , 5738120.1 , upper_inc =True)
    a3 = spans.floatrange(5737550.0 , 5738120.0,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)
    print "Works"

except:
    print "Fails"




# below FAILS when the span size is 0.1
try:
    a1 = spans.floatrange(1515737730.0 , 1515737730.1 , upper_inc =True)
    a2 = spans.floatrange(1515738120.0 , 1515738120.1 , upper_inc =True)
    a3 = spans.floatrange(1515737550.0 , 1515738120.0,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)
    print "Works"

except:
    print "Fails"
`

**Comment by Myrtillus** [comment]
`#!/usr/bin/env python
# -*- coding: latin 1 -*-

import spans
import pdb

try:
    a1 = spans.floatrange(10.,11.,upper_inc =True)
    a2 = spans.floatrange(20.,21.,upper_inc =True)
    a3 = spans.floatrange(15.,21.,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)
    print "Works"
except:
    print "Fails"



try:
    a1 = spans.floatrange(10.,10.1,upper_inc =True)
    a2 = spans.floatrange(20.,20.1,upper_inc =True)
    a3 = spans.floatrange(15.,20.1,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)
    print "Works"
except:
    print "Fails"



try:

    a1 = spans.floatrange(1515737730.0 , 1515737731.1 , upper_inc =True)
    a2 = spans.floatrange(1515738120.0 , 1515738121.1 , upper_inc =True)
    a3 = spans.floatrange(1515737550.0 , 1515738121.0,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)

    print "Works"

except:
    print "Fails"



try:
    a1 = spans.floatrange(7730.0 , 7730.1 , upper_inc =True)
    a2 = spans.floatrange(8120.0 , 8120.1 , upper_inc =True)
    a3 = spans.floatrange(7550.0 , 8120.0,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)

    print "Works"
except:
    print "Fails"




try:
    a1 = spans.floatrange(5737730.0 , 5737730.1 , upper_inc =True)
    a2 = spans.floatrange(5738120.0 , 5738120.1 , upper_inc =True)
    a3 = spans.floatrange(5737550.0 , 5738120.0,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)
    print "Works"

except:
    print "Fails"




try:
    a1 = spans.floatrange(1515737730.0 , 1515737730.1 , upper_inc =True)
    a2 = spans.floatrange(1515738120.0 , 1515738120.1 , upper_inc =True)
    a3 = spans.floatrange(1515737550.0 , 1515738120.0,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)
    print "Works"

except:
    print "Fails"









`

**Comment by Myrtillus** [comment]
#!/usr/bin/env python
# -*- coding: latin 1 -*-

import spans
import pdb

try:
    a1 = spans.floatrange(10.,11.,upper_inc =True)
    a2 = spans.floatrange(20.,21.,upper_inc =True)
    a3 = spans.floatrange(15.,21.,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)
    print "Works"
except:
    print "Fails"



try:
    a1 = spans.floatrange(10.,10.1,upper_inc =True)
    a2 = spans.floatrange(20.,20.1,upper_inc =True)
    a3 = spans.floatrange(15.,20.1,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)
    print "Works"
except:
    print "Fails"



try:

    a1 = spans.floatrange(1515737730.0 , 1515737731.1 , upper_inc =True)
    a2 = spans.floatrange(1515738120.0 , 1515738121.1 , upper_inc =True)
    a3 = spans.floatrange(1515737550.0 , 1515738121.0,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)

    print "Works"

except:
    print "Fails"



try:
    a1 = spans.floatrange(7730.0 , 7730.1 , upper_inc =True)
    a2 = spans.floatrange(8120.0 , 8120.1 , upper_inc =True)
    a3 = spans.floatrange(7550.0 , 8120.0,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)

    print "Works"
except:
    print "Fails"




try:
    a1 = spans.floatrange(5737730.0 , 5737730.1 , upper_inc =True)
    a2 = spans.floatrange(5738120.0 , 5738120.1 , upper_inc =True)
    a3 = spans.floatrange(5737550.0 , 5738120.0,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)
    print "Works"

except:
    print "Fails"




try:
    a1 = spans.floatrange(1515737730.0 , 1515737730.1 , upper_inc =True)
    a2 = spans.floatrange(1515738120.0 , 1515738120.1 , upper_inc =True)
    a3 = spans.floatrange(1515737550.0 , 1515738120.0,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)
    print "Works"

except:
    print "Fails"

**Comment by Myrtillus** [comment]
hmmm... below code would suggest that the problem comes from the accuracy of the floating point numbers in this case when the span is extended with 0.1 .

```python
#!/usr/bin/env python
# -*- coding: latin 1 -*-

import spans
import pdb

try:
    a1 = spans.floatrange(10.,11.,upper_inc =True)
    a2 = spans.floatrange(20.,21.,upper_inc =True)
    a3 = spans.floatrange(15.,21.,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)
    print "Works"
except:
    print "Fails"



try:
    a1 = spans.floatrange(10.,10.1,upper_inc =True)
    a2 = spans.floatrange(20.,20.1,upper_inc =True)
    a3 = spans.floatrange(15.,20.1,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)
    print "Works"
except:
    print "Fails"



try:

    a1 = spans.floatrange(1515737730.0 , 1515737731.1 , upper_inc =True)
    a2 = spans.floatrange(1515738120.0 , 1515738121.1 , upper_inc =True)
    a3 = spans.floatrange(1515737550.0 , 1515738121.0,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)

    print "Works"

except:
    print "Fails"



try:
    a1 = spans.floatrange(7730.0 , 7730.1 , upper_inc =True)
    a2 = spans.floatrange(8120.0 , 8120.1 , upper_inc =True)
    a3 = spans.floatrange(7550.0 , 8120.0,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)

    print "Works"
except:
    print "Fails"




try:
    a1 = spans.floatrange(5737730.0 , 5737730.1 , upper_inc =True)
    a2 = spans.floatrange(5738120.0 , 5738120.1 , upper_inc =True)
    a3 = spans.floatrange(5737550.0 , 5738120.0,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)
    print "Works"

except:
    print "Fails"




try:
    a1 = spans.floatrange(1515737730.0 , 1515737730.1 , upper_inc =True)
    a2 = spans.floatrange(1515738120.0 , 1515738120.1 , upper_inc =True)
    a3 = spans.floatrange(1515737550.0 , 1515738120.0,upper_inc =True)

    aa1 = spans.floatrangeset([a1,a2])
    aa2 = spans.floatrangeset([a3])

    aa3 = aa1.union(aa2)
    print "Works"

except:
    print "Fails"


```

**Comment by runfalk** [comment]
@Myrtillus I tried your testcases with 1.0.2 that I just released on PyPI. They all work. Please try it out and report back if your issues aren't fixed.

**Comment by Myrtillus** [comment]
The first impression is that problem is solved. Thank  you very much!

**Comment by runfalk** [comment]
Great! Please open a new issue if you have any trouble.
