### ISSUE TITLE
Docs & version 1.1.0

### ISSUE THREAD

**Issue by aklaver** [runfalk/spans#15]
The docs(https://spans.readthedocs.io/en/latest/changelog.html) do not seem to have caught up with version 1.1.0.

**Comment by runfalk** [comment]
It seems like I never configured it to update automatically. I refreshed the build and set up webhooks to make sure it stays in sync. Thank you for reporting this!

https://spans.readthedocs.io/ (you may need to refresh with ctrl+r or wipe your cache).

**Comment by aklaver** [comment]
Thanks.
