### ISSUE TITLE
Intersection of multiple range sets is not working properly

### ISSUE THREAD

**Issue by der-michik** [runfalk/spans#3]
When calculating the intersection of multiple sets, only elements should be returned that are present of every set within the intersection (and this is what the docstring says one should expect). This works as intended when intersecting two sets:

    In [1]: from spans import intrange, intrangeset
    In [2]: r1 = intrange(1, 3)
    In [3]: r2 = intrange(5, 7)
    In [4]: s1 = intrangeset([r1])
    In [5]: s2 = intrangeset([r2])
    In [6]: s1.intersection(s2)
    Out[6]: intrangeset([])

However, when intersecting multiple sets, it seems to intersect the union of all arguments with the first set:

    In [7]: r3 = intrange(9, 11)
    In [8]: s1 = intrangeset([r1, r2])
    In [9]: s2 = intrangeset([r2])
    In [10]: s3 = intrangeset([r3])
    In [11]: s1.intersection(s2, s3)
    Out[11]: intrangeset([intrange([5,7))])

Compare this to intersecting them one by one:

    In [12]: s1.intersection(s2).intersection(s3)
    Out[12]: intrangeset([])

I will see if I can patch this properly and send you a pull request, but for the moment, the workaround with intersecting one by one has to do for me.

**Comment by runfalk** [comment]
Thank you for reporting this. I have made a fix that will be included in the next release. If no other issues are reported within the next week I will make a new release, unless you would like me to release this more urgently?

Let me know if this fix works for your use case.

**Comment by der-michik** [comment]
Thanks for the prompt fix. I just tested it and it seems to work fine. Makes my code look a bit cleaner.

However, I think I just found another bug - I will investigate and open a new issue for that.

**Comment by runfalk** [comment]
Great! I will close this issue then.
