### ISSUE TITLE
Why different type checking is used for daterange?

### ISSUE THREAD

**Issue by AlexBazer** [runfalk/spans#5]
As I see, for other types, **datetimerange** for example, you used *isinstance*, but for **daterange** you've used ```type(lower) is not date```.
https://github.com/runfalk/spans/blob/master/spans/types.py#L964

I encounter a problem while using freezegun (https://github.com/spulec/freezegun) alongside with spans.
Freezgun uses custom FakeDate class that have same interface as datetime.date, so daterange can't be created for FakeDate objects.

**Comment by runfalk** [comment]
The reasoning is that ``datetime`` subclasses ``date``. I want the type checking to be very strict, since it is very important to the database. The solution is most likely to allow subclasses of ``date`` that are not subclasses of ``datetime``. I will likely look into it later this week.

**Comment by AlexBazer** [comment]
Thank you for response, i totally forget that *date* is a subclass of *datetime*.
I will wait for you update then.

**Comment by runfalk** [comment]
The ``date`` subclassing is a bit unexpected, though it makes sense in a lot of cases I guess.

I have applied a fix that should work. Please try it for your usecase and report back here. If it works, I will make a new release in a week or so if there are no other issues.

I'm always happy for pull requests, so don't hesitate to send them for bugs like this ~~if~~ you find more of them.

**Comment by AlexBazer** [comment]
I've tried your last changes, they are working as expected.
Thank you!=)
